BulkyBookWeb/Areas/Admin/Controllers/ApplicationUserController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    public class ApplicationUserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ApplicationUserController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<ApplicationUser> objApplicationUserList = _unitOfWork.ApplicationUser.GetAll();
            return View(objApplicationUserList);
        }
        //GET
        public IActionResult Create()
        {   
            return View();
        }

    }
}

BulkyBookWeb/Areas/Admin/Controllers/RequestController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    public class RequestController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;
        public RequestController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;

        }
        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Home()
        {

            return View();
        }


        public IActionResult Upsert(int? id)
        {
            RequestVM requestVM = new()
            {
                Request = new(),
                RequirementList = _unitOfWork.Requirement.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString(),
                }),

            };

            if (id == null || id == 0)
            {
                return View(requestVM);
            }
            else
            {
                requestVM.Request = _unitOfWork.Request.GetFirstOrDefault(u => u.Id == id);
                return View(requestVM);

            }
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(RequestVM obj)
        { 
            if (ModelState.IsValid)
            {
                if (obj.Request.Id == 0)
                {
                    _unitOfWork.Request.Add(obj.Request);
                    TempData["success"] = "Request created successfully";
                }
                else
                {
                    _unitOfWork.Request.Update(obj.Request);
                    TempData["success"] = "Request updated successfully";
                }
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        #region API CALLS
        [HttpGet]

        public IActionResult GetAll()
        {
            var requestList = _unitOfWork.Request.GetAll(includeProperties: "Requirement");
            return Json(new { data = requestList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Request.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _unitOfWork.Request.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Succesful" });

        }
        #endregion

    }
}

BulkyBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Concordia S.A.</title>
    <link rel="stylesheet" href="~/css/BTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarColor   02">
      <ul class="navbar-nav me-auto">
    @if (User.IsInRole("Admin") || User.IsInRole("Employee") || User.IsInRole("Support"))
    {
        <li class="nav-item">
          <a class="nav-link" asp-area="Admin" asp-controller="Request" asp-action="Index">Solicitudes</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" asp-area="Admin" asp-controller="Requirement" asp-action="Index">Requerimientos</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" asp-area="Admin" asp-controller="ApplicationUser" asp-action="Index">Usuarios</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" asp-area="Admin" asp-controller="Assignation" asp-action="Index">Asignaciones</a>
          </li>
    }



      </ul>
      <partial name="_LoginPartial"/>
    @*  <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>*@
    </div>
  </div>
</nav>
       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"/>
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-primary">
        <div class="container">
            &copy; 2022 - Concordia S.A. 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyBookWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');

    </script>
}
@if (TempData["error"] != null)
{
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"> </script>
        <script type="text/javascript">
         toastr.error('@TempData["error"]');
         </script>
   
}