BulkyBookWeb/Areas/Admin/Controllers/RequirementController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Support, Employee")]
    public class RequirementController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public RequirementController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Requirement> objRequirementList = _unitOfWork.Requirement.GetAll();
            return View(objRequirementList);
        }
        //GET
        public IActionResult Create()
        {   
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Requirement obj)
        {
            
            if (ModelState.IsValid)
            {
                _unitOfWork.Requirement.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Requerimiento creado exitosamente";
                return RedirectToAction("Index");
            }
            return View(obj);   
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id);
            var RequirementFromDbFirst = _unitOfWork.Requirement.GetFirstOrDefault(u => u.Id == id);

            if(RequirementFromDbFirst == null)
                {
                    return NotFound();
                } 
            return View(RequirementFromDbFirst);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Requirement obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Requirement.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Requerimiento actualizado correctamente";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var RequirementFromDbFirst = _unitOfWork.Requirement.GetFirstOrDefault(u => u.Id == id);
            if (RequirementFromDbFirst == null)
            {
                return NotFound();
            }
            return View(RequirementFromDbFirst);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.Requirement.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Requirement.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Requerimiento borrado exitosamente";
            return RedirectToAction("Index");
            
            return View(obj);
        }
    }
}

BulkyBookWeb/Areas/Admin/Views/Requirement/Create.cshtml
@model BulkyBook.Models.Requirement
<form method="post">
    <div class="border p-4 mt-4">
       <div class="row pb-2">
           <h2 class="text-primary">Crear nuevo requerimiento</h2>
           <hr />
       </div>
       <div asp-validation-summary="All"></div>
       <div class="nb-3">
           <label asp-for="Name"></label>
           <input asp-for="Name" class="form-control"/>
           <span asp-validation-for="Name" class="text-danger"></span>
       <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
       <a asp-controller="Requirement" asp-action="Index" class="btn btn-secondary" style="width:150px" >
           Back to List
       </a>
    </div>
</form>

@section Scripts {
    @{
            <partial name="_ValidationScriptsPartial"></partial>
    }
}


 


        
       
         

BulkyBookWeb/Areas/Admin/Views/Requirement/Delete.cshtml
@model Requirement
<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden/>
    <div class="border p-4 mt-4">
       <div class="row pb-2">
           <h2 class="text-primary">Delete CoverType</h2>
           <hr />
       </div>
       <div asp-validation-summary="All"></div>
       <div class="nb-3">
           <label asp-for="Name"></label>
           <input asp-for="Name" disabled class="form-control"/>
       </div>
       <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
       <a asp-controller="Requirement" asp-action="Index" class="btn btn-secondary" style="width:150px" >
           Back to List
       </a>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}


 


        
       
         

BulkyBookWeb/Areas/Admin/Views/Requirement/Edit.cshtml
@model Requirement
<form method="post" asp-action="Edit">
    <div class="border p-4 mt-4">
       <div class="row pb-2">
           <h2 class="text-primary">Editar Requerimiento
           </h2>
           <hr />
       </div>
       <div asp-validation-summary="All"></div>
       <div class="nb-3">
           <label asp-for="Name"></label>
           <input asp-for="Name" class="form-control"/>
           <span asp-validation-for="Name" class="text-danger"></span>
       </div>
       <button type="submit" class="btn btn-primary" style="width:150px">Actualizar</button>
       <a asp-controller="Requirement" asp-action="Index" class="btn btn-secondary" style="width:150px" >
           Regresar a la lista
       </a>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}


 


        
       
         

BulkyBookWeb/Areas/Admin/Views/Requirement/Index.cshtml
@using BulkyBook.Models.ViewModels
@model IEnumerable<Requirement> 
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Listado de requerimientos</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Requirement" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp;  Crear requerimiento nuevo
            </a>
        </div>
    </div>


    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Nombre de requerimiento
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%">
                        @obj.Name
                    </td>
                    <td>
                        <div class="w-75 btn-group=" role="group">
                            <a asp-controller="Requirement" asp-action="Edit" asp-route-id="@obj.Id"
                            class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i> Edit </a>
                             <a asp-controller="Requirement" asp-action="Delete" asp-route-id="@obj.Id"
                            class="btn btn-danger mx-2"><i class="bi bi-trash3-fill"></i> Delete </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>

</div>